# -*- coding: utf-8 -*-
"""scraiping_practice

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1MPrgu7_9CFgj85u3wN_IVs6UEyOqACgQ
"""

from bs4 import BeautifulSoup
import requests
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
import warnings
warnings.filterwarnings('ignore')
import urllib3
from urllib3.exceptions import InsecureRequestWarning
urllib3.disable_warnings(InsecureRequestWarning)

url_card_rush = "https://www.cardrush.jp/product/65185"
response = requests.get(url_card_rush)
soup = BeautifulSoup(response.text, "html.parser")

price = soup.find("div", attrs={"class":"detail_section price"})
price = price.find("span",attrs={"class":"figure"})
price= price.get_text()



url_beems="https://www.cardshopbeems-yugioh.com/SHOP/A04291.html"
response = requests.get(url_beems,verify=False)
soup = BeautifulSoup(response.text, "html.parser")

"ポッキー"
















